# Generated by Django 4.2 on 2024-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategorycomponent',
            old_name='info_text',
            new_name='info_name',
        ),
        migrations.RenameField(
            model_name='productcomponents',
            old_name='info_text_category',
            new_name='info_name_category',
        ),
        migrations.RenameField(
            model_name='productcomponents',
            old_name='info_name',
            new_name='info_text',
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
