# Generated by Django 4.2 on 2024-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomponents',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='productcomponents',
            name='info_name_category',
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductCategoryComponent',
        ),
    ]
