# Generated by Django 4.2 on 2024-11-30 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productcomponents_extra_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Form',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('pickup_type', models.CharField(choices=[('delivery', 'delivery'), ('takefrom_here', 'takefrom_here')], max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('pickup_address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('is_checked', models.BooleanField(default=False)),
                ('delivery_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.delivery_form')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
