# Generated by Django 4.2 on 2024-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delivery_form_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandproduct',
            options={'verbose_name': 'Mahsulotlarning Brandi'},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Mahsulotlar Kategoriyasi', 'verbose_name_plural': 'Mahsulotlar Kategoriyasi'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Buyurtmadagi mahsulot', 'verbose_name_plural': 'Buyurtmadagi mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productcolour',
            options={'verbose_name': 'Mahsulot rang', 'verbose_name_plural': 'Mahsulot ranglari'},
        ),
        migrations.AlterModelOptions(
            name='productcomponents',
            options={'verbose_name': 'Mahsulot xususiyat', 'verbose_name_plural': 'Mahsulot xususiyatlari'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Mahsulot rasm', 'verbose_name_plural': 'Mahsulot rasmlari'},
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_text_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_text_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productcomponents',
            name='info_text_uz',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
