# Generated by Django 4.2 on 2024-11-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='adversitement',
            name='image_en',
            field=models.ImageField(null=True, upload_to='common/advertisement'),
        ),
        migrations.AddField(
            model_name='adversitement',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='common/advertisement'),
        ),
        migrations.AddField(
            model_name='adversitement',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='common/advertisement'),
        ),
    ]
